// e:\GitHub\Buriti_MAPA_UFU\js\config.example.js
//
// Example Configuration for Mapbox Access Token
//
// For local development:
// 1. Copy this file to `js/config.js`.
// 2. Uncomment the line below and replace 'YOUR_MAPBOX_ACCESS_TOKEN_HERE'
//    with your actual Mapbox access token.
//
// For GitHub Pages deployment:
// - The actual `js/config.js` file will be generated by a GitHub Actions workflow
//   using a secret token stored in your repository settings.
// - Ensure `js/config.js` is listed in your `.gitignore` file.
//
// Your main script should import the token like this:
// import { MAPBOX_ACCESS_TOKEN } from './config.js'; // Adjust path if needed
// mapboxgl.accessToken = MAPBOX_ACCESS_TOKEN;

// Uncomment and replace in your actual `js/config.js` (for local development)
// or this line will be generated by GitHub Actions for deployment:
// export const MAPBOX_ACCESS_TOKEN = 'YOUR_MAPBOX_ACCESS_TOKEN_HERE';